---
- hosts: localhost
  name: Create vSphere tag-based storage policy for TKG 
  gather_facts: false
  vars_files: ../answerfile.yml

  tasks:
    
    - name: Create or update a vSphere tag-based storage policy
      community.vmware.vmware_vm_storage_policy:
        validate_certs: no
        hostname: '{{ vcenter_hostname }}.{{ domain }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        name: '{{ vsphere_storage_policy_name }}'
        description: '{{ vsphere_storage_policy_description }}'
        tag_category: '{{ vsphere_storage_policy_tag_category }}'
        tag_name: '{{ vsphere_storage_policy_tag_name }}'
        tag_affinity: true
        state: "present"
      delegate_to: localhost