---
- hosts: localhost
  name: Networking
  gather_facts: false
  vars_files: ../answerfile.yml

  tasks:
    - name: Create dvSwitch with all options
      community.vmware.vmware_dvswitch:
        validate_certs: no
        hostname: '{{ vcenter_hostname }}.{{ domain }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        datacenter: '{{ datacenter_name }}'
        switch: '{{ dvSwitch_name }}'
        version: 7.0.2
        mtu: 9000
        uplink_quantity: 4
        uplink_prefix: 'Uplink_'
        discovery_protocol: cdp
        discovery_operation: both
        multicast_filtering_mode: snooping
        health_check:
          #vlan_mtu: true
          #vlan_mtu_interval: 1
          teaming_failover: true
          teaming_failover_interval: 1
        state: present
      delegate_to: localhost



    - name: Create vlan portgroup with all security and port policies
      community.vmware.vmware_dvs_portgroup:
        validate_certs: no
        hostname: '{{ vcenter_hostname }}.{{ domain }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        portgroup_name: vlan-10-MGMT
        switch_name: '{{ dvSwitch_name }}'
        vlan_id: 10
        num_ports: 120
        portgroup_type: earlyBinding
        state: present
        network_policy:
          promiscuous: true
          forged_transmits: false
          mac_changes: true
        port_policy:
          block_override: true
          ipfix_override: true
          live_port_move: true
          network_rp_override: true
          port_config_reset_at_disconnect: true
          security_override: true
          shaping_override: true
          traffic_filter_override: true
          uplink_teaming_override: true
          vendor_config_override: true
          vlan_override: true
      delegate_to: localhost


    - name: Create vlan portgroup with all security and port policies
      community.vmware.vmware_dvs_portgroup:
        validate_certs: no
        hostname: '{{ vcenter_hostname }}.{{ domain }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        portgroup_name: vlan-04-VMOTION
        switch_name: '{{ dvSwitch_name }}'
        vlan_id: 4
        num_ports: 120
        portgroup_type: earlyBinding
        state: present
        network_policy:
          promiscuous: true
          forged_transmits: false
          mac_changes: true
        port_policy:
          block_override: true
          ipfix_override: true
          live_port_move: true
          network_rp_override: true
          port_config_reset_at_disconnect: true
          security_override: true
          shaping_override: true
          traffic_filter_override: true
          uplink_teaming_override: true
          vendor_config_override: true
          vlan_override: true
      delegate_to: localhost


    - name: Create vlan portgroup with all security and port policies
      community.vmware.vmware_dvs_portgroup:
        validate_certs: no
        hostname: '{{ vcenter_hostname }}.{{ domain }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        portgroup_name: vlan-08-VSAN
        switch_name: '{{ dvSwitch_name }}'
        vlan_id: 8
        num_ports: 120
        portgroup_type: earlyBinding
        state: present
        network_policy:
          promiscuous: true
          forged_transmits: false
          mac_changes: true
        port_policy:
          block_override: true
          ipfix_override: true
          live_port_move: true
          network_rp_override: true
          port_config_reset_at_disconnect: true
          security_override: true
          shaping_override: true
          traffic_filter_override: true
          uplink_teaming_override: true
          vendor_config_override: true
          vlan_override: true
      delegate_to: localhost





    - name: Create vlan portgroup with all security and port policies
      community.vmware.vmware_dvs_portgroup:
        validate_certs: no
        hostname: '{{ vcenter_hostname }}.{{ domain }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        portgroup_name: vlan-06-OVERLAY
        switch_name: '{{ dvSwitch_name }}'
        vlan_id: 6
        num_ports: 120
        portgroup_type: earlyBinding
        state: present
        network_policy:
          promiscuous: true
          forged_transmits: false
          mac_changes: true
        port_policy:
          block_override: true
          ipfix_override: true
          live_port_move: true
          network_rp_override: true
          port_config_reset_at_disconnect: true
          security_override: true
          shaping_override: true
          traffic_filter_override: true
          uplink_teaming_override: true
          vendor_config_override: true
          vlan_override: true
      delegate_to: localhost      

    - name: Create vlan portgroup with all security and port policies
      community.vmware.vmware_dvs_portgroup:
        validate_certs: no
        hostname: '{{ vcenter_hostname }}.{{ domain }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        portgroup_name: vlan-11-EDGE-UPLINK
        switch_name: '{{ dvSwitch_name }}'
        vlan_id: 11
        num_ports: 120
        portgroup_type: earlyBinding
        state: present
        network_policy:
          promiscuous: true
          forged_transmits: false
          mac_changes: true
        port_policy:
          block_override: true
          ipfix_override: true
          live_port_move: true
          network_rp_override: true
          port_config_reset_at_disconnect: true
          security_override: true
          shaping_override: true
          traffic_filter_override: true
          uplink_teaming_override: true
          vendor_config_override: true
          vlan_override: true
      delegate_to: localhost            