---
- hosts: localhost
  name: Add Hosts and licenses to vCenter 
  gather_facts: false
  vars_files: ../answerfile.yml

  tasks:

    - name: Create distributed switch in the nested vCenter
      vmware_dvswitch:
        hostname: '{{ vcenter_hostname }}.{{ domain }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        datacenter_name: '{{ datacenter_name }}'
        validate_certs: false
        switch_name: '{{ dvSwitch_name }}'
        switch_version: '7.0.2'
        mtu: "9000"
        uplink_quantity: "4"
        discovery_proto: "cdp"
        discovery_operation: "both"
        state: present

    - name: Create Management port group
      vmware_dvs_portgroup:
        hostname: '{{ vcenter_hostname }}.{{ domain }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: false
        portgroup_name: vlan-10-MGMT
        switch_name: '{{ dvSwitch_name }}'
        vlan_id: 10
        num_ports: 8
        portgroup_type: earlyBinding
        state: present

    - name: Create vMotion port group
      vmware_dvs_portgroup:
        hostname: '{{ vcenter_hostname }}.{{ domain }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: false
        portgroup_name: vlan-04-VMOTION
        switch_name: '{{ dvSwitch_name }}'
        vlan_id: 4
        num_ports: 8
        portgroup_type: earlyBinding
        state: present

    - name: Create vSAN port group
      vmware_dvs_portgroup:
        hostname: '{{ vcenter_hostname }}.{{ domain }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: false
        portgroup_name: vlan-08-VSAN
        switch_name: '{{ dvSwitch_name }}'
        vlan_id: 8
        num_ports: 8
        portgroup_type: earlyBinding
        state: present

    - name: Create Overlay port group
      vmware_dvs_portgroup:
        hostname: '{{ vcenter_hostname }}.{{ domain }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: false
        portgroup_name: vlan-06-OVERLAY
        switch_name: '{{ dvSwitch_name }}'
        vlan_id: 6
        num_ports: 8
        portgroup_type: earlyBinding
        state: present

    - name: Create SVM-Management port group
      vmware_dvs_portgroup:
        hostname: '{{ vcenter_hostname }}.{{ domain }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: false
        portgroup_name: vlan-11-EDGE-UPLINK
        switch_name: '{{ dvSwitch_name }}'
        vlan_id: 11
        num_ports: 8
        portgroup_type: earlyBinding
        state: present


    - name: Create VMNetwork port group
      vmware_dvs_portgroup:
        hostname: '{{ vcenter_hostname }}.{{ domain }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: false
        portgroup_name: vlan-10-MGMT
        switch_name: '{{ dvSwitch_name }}'
        vlan_id: 10
        num_ports: 8
        portgroup_type: earlyBinding
        state: present

    - name: Migrate uplinks to the VDS
      vmware_dvs_host:
        hostname: '{{ vcenter_hostname }}.{{ domain }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: false
        esxi_hostname: "{{ esxi_compute_03_fqdn }}"
        switch_name: '{{ dvSwitch_name }}'
        vmnics:
          - vmnic1
          #- vmnic2
        state: present


    - name: Migrate vmk0 to the VDS
      vmware_migrate_vmk:
        hostname: '{{ vcenter_hostname }}.{{ domain }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: false
        esxi_hostname: "{{ esxi_compute_03_fqdn }}"
        device: 'vmk0'
        current_switch_name: 'vSwitch0'
        current_portgroup_name: 'Management Network'
        migrate_switch_name: '{{ dvSwitch_name }}'
        migrate_portgroup_name: vlan-10-MGMT


    - name: Create vmk1 for vMotion
      community.vmware.vmware_vmkernel:
        hostname: '{{ vcenter_hostname }}.{{ domain }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: false
        esxi_hostname: "{{ esxi_compute_03_fqdn }}"
        portgroup_name: vlan-04-VMOTION
        dvswitch_name: '{{ dvSwitch_name }}'
        enable_vmotion: true
        network:
          type: 'static'
          ip_address: 10.0.4.36
          subnet_mask: 255.255.255.0
          default_gateway: 10.0.4.253
          tcpip_stack: vmotion
        state: present
        mtu: 9000


    - name: Create vmk2 for vSAN
      community.vmware.vmware_vmkernel:
        hostname: '{{ vcenter_hostname }}.{{ domain }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: false
        esxi_hostname: "{{ esxi_compute_03_fqdn }}"
        portgroup_name: vlan-08-VSAN
        dvswitch_name: '{{ dvSwitch_name }}'
        enable_vsan: true
        network:
          type: 'static'
          ip_address: 10.0.8.36
          subnet_mask: 255.255.255.0
          default_gateway: 10.0.8.253
          tcpip_stack: default
        state: present
        mtu: 9000

      

      
    - name: Remove the standard switch from the ESXi hosts
      vmware_vswitch:
        hostname: "{{ esxi_compute_03_fqdn }}"
        username: root
        password: 20Start!Lab20
        validate_certs: false
        switch: 'vSwitch0'
        state: absent


    - name: Migrate uplinks to the VDS
      vmware_dvs_host:
        hostname: '{{ vcenter_hostname }}.{{ domain }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: false
        esxi_hostname: "{{ esxi_compute_03_fqdn }}"
        switch_name: '{{ dvSwitch_name }}'
        vmnics:
          - vmnic0
          - vmnic1
        state: present


